FROM python:3.7.9-stretch

RUN pip install requests
RUN pip install jsons
RUN pip install pymysql
RUN pip install python-consul
RUN pip install threaded
RUN pip install Flask
RUN pip install Flask-RESTful
RUN pip install Flask-JWT-Extended
RUN pip install Flask-Cors

COPY ./school_server ./school_server
WORKDIR /school_server
CMD ["python", "run.py"]